FROM node
RUN npm install -g create-react-app
#RUN create-react-app /tmp/myapp
#WORKDIR /tmp/myapp
#ADD ./ /tmp/myapp
EXPOSE 3000
CMD bash
#CMD ["npm","start"]

docker run -it --rm --name reacr -v /home/antonio/Documentos/estudos/docker/imagens/react/:/home/app:rw node-react
